version: '3'

services:
  database:
    container_name: 'dragons-api_database'
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=dragons'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=toothless'
    ports:
      - '5432:5432'
